language: node_js
os:
- linux
- osx
cache:
  yarn: true
  directories:
  - "$HOME/.esy"
node_js:
- '11'
install:
- npm install -g esy
script:
- npm run build
- mv _esy/default/build/default/.ppx/let_anything_ppx/ppx.exe ppx-$TRAVIS_OS_NAME.exe
deploy:
  provider: releases
  edge: true
  skip_cleanup: true
  file_glob: true
  file: ppx-*.exe
  overwrite: true
  api_key: $GITHUB_KEY
  on:
    tags: true
    branch: master
    repo: mrmurphy/let-anything
jobs:
  include:
    matrix:
    - stage: deploy
      script: skip
      before_deploy:
      - curl -OL https://github.com/mrmurphy/let-anything/releases/download/$TRAVIS_TAG/ppx-linux.exe
      - curl -OL https://github.com/mrmurphy/let-anything/releases/download/$TRAVIS_TAG/ppx-osx.exe
      - chmod +x *.exe
      deploy:
        skip_cleanup: true
        provider: npm
        edge: true
        email: m@mrmurphy.dev
        on:
          tags: true
          branch: master
        api_key: $NPM_KEY
